name: Full Testing CPU

on:
  workflow_dispatch:

jobs:

  test_all_versions:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.10']
        torch-version: [1.13.0, 2.0.0, 2.1.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          torch-version: ${{ matrix.torch-version }}

      - name: Install main package
        run: |
          pip install -e .[test]

      - name: Run tests
        run: |
          pytest
        shell: bash
